CsvSeparator = ";"
Parameters = "out/Parameters.csv"

[[Tables]]
Observer = "obs.WorkerCohorts"
File = "out/WorkerCohorts.csv"

[[TimeSeriesPlots]]
Observer = "obs.WorkerCohorts"
Params = { Cumulative = true }
DrawInterval = 5
MaxRows = 730
Bounds = {X=1, Y=30, W=600, H=400}
Labels = {Title="WorkerCohorts", X="Time [d]", Y="Count"}

[[TimeSeriesPlots]]
Observer = "obs.Stores"
Params = { PollenFactor = 20 }
DrawInterval = 5
MaxRows = 730
Bounds = {X=1, Y=470, W=600, H=400}
Labels = {Title="Stores", X="Time [d]", Y="Amount [kg]"}
